import type { Pattern } from './types'

/** Advanced / contemporary UX patterns beyond the core set */
export const advancedPatterns: Pattern[] = [
  {
    id: 'command-palette',
    nameZh: '命令面板',
    nameEn: 'Command Palette',
    aliases: ['⌘K', 'Spotlight'],
    category: 'advanced',
    summary: '可搜索的命令启动器，用键盘快速执行任意操作。',
    definition: '全局浮层列出可搜索命令与跳转目标，通常由 ⌘K / Ctrl+K 打开，支持模糊匹配与键盘选择。',
    whenToUse: ['桌面端工具型产品', '命令/页面很多，鼠标找菜单成本高', '效率用户是核心人群'],
    whenNotToUse: ['纯消费型移动 App', '命令极少（直接放工具栏即可）'],
    variants: ['仅命令', '命令+文件/人', '分组与近期'],
    related: ['debounced-search', 'modal'],
    collab: {
      states: ['closed', 'open', 'querying', 'selected'],
      api: ['本地命令注册表；远程结果需防抖与取消'],
      productNotes: ['默认快捷键要可发现；空态展示高频命令'],
    },
    confuseWith: [{ id: 'debounced-search', note: '搜索偏找内容；命令面板偏执行动作' }],
  },
  {
    id: 'bottom-sheet',
    nameZh: '底部 Sheet',
    nameEn: 'Bottom Sheet',
    category: 'overlays',
    summary: '从底部升起、可吸附多档高度的面板，移动端详情与操作首选。',
    definition: '自屏幕底部滑入的面板，常支持半屏/全屏等 snap 点，可拖拽调整高度。',
    whenToUse: ['移动端详情、筛选、操作列表', '需要保留部分背景上下文'],
    whenNotToUse: ['桌面宽屏长表单（用 Modal/侧栏）', '必须强阻断的法律确认'],
    variants: ['固定半屏', '多档吸附', '内容驱动高度'],
    related: ['drawer', 'modal', 'confirm-dialog'],
    collab: {
      states: ['collapsed', 'half', 'full', 'dragging'],
      api: ['打开时按需拉详情；关闭丢弃未保存需拦截'],
      productNotes: ['提供关闭按钮，不只依赖下滑'],
    },
    confuseWith: [{ id: 'drawer', note: '抽屉多从侧边；Sheet 从底部且常有吸附' }],
  },
  {
    id: 'ghost-text',
    nameZh: '幽灵文本补全',
    nameEn: 'Ghost Text Completion',
    category: 'ai',
    summary: '以淡色预填建议，Tab 接受——IDE 与 AI 写作标配。',
    definition: '在光标后以低对比度显示模型建议文本，用户可用快捷键接受、逐词接受或忽略。',
    whenToUse: ['代码/文案辅助输入', '建议可局部接受'],
    whenNotToUse: ['建议准确率很低（干扰大于帮助）', '强合规场景禁止自动建议'],
    variants: ['整段接受', '逐词', '多候选切换'],
    related: ['streaming-output', 'suggestion-chips'],
    collab: {
      states: ['idle', 'suggesting', 'accepted', 'dismissed'],
      api: ['流式补全接口；需 debounce 与文档上下文'],
      productNotes: ['明确「Tab 接受」提示；可一键关闭 AI'],
    },
    confuseWith: [{ id: 'autocomplete', note: '下拉候选 vs 行内幽灵文本' }],
  },
  {
    id: 'streaming-output',
    nameZh: '流式输出',
    nameEn: 'Streaming Output',
    category: 'ai',
    summary: '模型回答逐字出现，并支持停止生成。',
    definition: '通过 SSE/WebSocket 逐 token 渲染回复，缩短首字时间；提供停止以中断生成。',
    whenToUse: ['对话式 AI', '长文生成需要即时反馈'],
    whenNotToUse: ['必须完整校验后再展示的结果', '极短确定性回答'],
    variants: ['打字机', '按块 Markdown', '带停止按钮'],
    related: ['ghost-text', 'suggestion-chips', 'skeleton'],
    collab: {
      states: ['connecting', 'streaming', 'stopped', 'done', 'error'],
      api: ['可取消的流；停止后保存已生成部分'],
      productNotes: ['停止后允许续写/重试；展示来源时勿闪烁过频'],
    },
    confuseWith: [{ id: 'skeleton', note: '骨架是占位；流式是真实内容渐进出现' }],
  },
  {
    id: 'suggestion-chips',
    nameZh: '建议芯片',
    nameEn: 'Suggestion Chips',
    category: 'ai',
    summary: '可点击的推荐追问或快捷指令，降低空白输入成本。',
    definition: '以芯片/标签形式展示下一句建议或预设 Prompt，点击即填入或发送。',
    whenToUse: ['对话空态与回合结束后', '引导探索能力边界'],
    whenNotToUse: ['建议与上下文无关变成噪音'],
    variants: ['发送即走', '填入可编辑', '分组建议'],
    related: ['streaming-output', 'command-palette'],
    collab: {
      states: ['visible', 'selected'],
      api: ['可由模型返回 suggested_replies[]'],
      productNotes: ['控制数量 3–5；文案短'],
    },
    confuseWith: [{ id: 'chip-input', note: '芯片输入是编辑多值；建议芯片是快捷动作' }],
  },
  {
    id: 'tool-call-confirm',
    nameZh: '工具调用确认',
    nameEn: 'Tool Call Confirmation',
    category: 'ai',
    summary: 'Agent 调用外部工具或产生副作用前，请人确认。',
    definition: '展示将要执行的工具、参数与影响，用户批准或拒绝后再继续代理流程。',
    whenToUse: ['发邮件、改库、付款、删数据等副作用', '企业 Agent 合规要求'],
    whenNotToUse: ['纯只读查询可自动执行'],
    variants: ['单次确认', '会话级白名单', '参数可编辑后确认'],
    related: ['confirm-dialog', 'streaming-output'],
    collab: {
      states: ['pending_approval', 'approved', 'rejected'],
      api: ['工具调用挂起直到 human_approval'],
      productNotes: ['说清不可逆影响；默认拒绝更安全'],
    },
    confuseWith: [{ id: 'confirm-dialog', note: '确认框通用；此模式绑定 Agent 工具链' }],
  },
  {
    id: 'swipe-action',
    nameZh: '滑动露出操作',
    nameEn: 'Swipe to Reveal Actions',
    category: 'controls',
    summary: '列表行左右滑动露出删除、归档等快捷操作。',
    definition: '在移动列表中水平拖动一行，露出彩色操作区，松手达阈值即触发。',
    whenToUse: ['邮件、待办、消息列表的高频操作', '移动优先'],
    whenNotToUse: ['桌面端（用悬停操作或菜单）', '与水平滚动容器冲突'],
    variants: ['单侧', '双侧', '完全滑出即删'],
    related: ['confirm-dialog', 'toast', 'bulk-action-bar'],
    collab: {
      states: ['rest', 'dragging', 'armed', 'committed'],
      api: ['提交突变；提供 Undo 窗口更佳'],
      productNotes: ['危险操作可二次确认或强 Undo'],
    },
    confuseWith: [{ id: 'drag-reorder', note: '一个是行内操作，一个是改顺序' }],
  },
  {
    id: 'card-stack',
    nameZh: '卡片堆叠滑动',
    nameEn: 'Card Stack / Swipe Deck',
    category: 'advanced',
    summary: '叠放卡片左右滑做选择，常见于匹配与决策流。',
    definition: '一次展示顶层卡片，用户左右滑动（或点按钮）表示接受/跳过，带旋转与离场动效。',
    whenToUse: ['招聘筛选、内容策展、偏好采集', '决策二元且节奏快'],
    whenNotToUse: ['需要并排比较多项', '可访问性要求极高且无按钮替代'],
    variants: ['仅按钮', '手势+按钮', '多方向含义'],
    related: ['swipe-action', 'optimistic-ui'],
    collab: {
      states: ['deck', 'flying', 'empty'],
      api: ['每次决策 POST；可预取下一批卡片'],
      productNotes: ['必须有非手势替代按钮'],
    },
    confuseWith: [{ id: 'carousel', note: '轮播是浏览；堆叠滑动是决策' }],
  },
  {
    id: 'before-after',
    nameZh: '前后对比滑杆',
    nameEn: 'Before / After Slider',
    category: 'advanced',
    summary: '拖动分割线对比处理前后的图像或界面。',
    definition: '同一视口内两层内容由可拖分割线揭示，用于修图、改版对比等。',
    whenToUse: ['视觉差异讲解', '营销与设计评审'],
    whenNotToUse: ['差异主要是文字而非视觉'],
    variants: ['水平', '垂直', '自动往返演示'],
    related: ['carousel'],
    collab: {
      states: ['position'],
      api: ['纯前端资源即可'],
      productNotes: ['提供键盘左右调节'],
    },
    confuseWith: [{ id: 'carousel', note: '轮播切换整页；对比滑杆同时看两边' }],
  },
  {
    id: 'scroll-snap',
    nameZh: '滚动吸附',
    nameEn: 'Scroll Snap',
    category: 'scrolling',
    summary: '滚动结束后对齐到预设停靠点，适合全屏叙事与卡片轨。',
    definition: 'CSS scroll-snap 或等效逻辑让滚动停在分页点，减少半截停驻。',
    whenToUse: ['故事型落地页', '水平产品卡片轨'],
    whenNotToUse: ['长文档阅读（强制吸附烦人）'],
    variants: ['强制吸附', '邻近吸附', '水平/垂直'],
    related: ['carousel', 'parallax'],
    collab: {
      states: ['index'],
      api: ['可把当前屏写入 URL hash'],
      productNotes: ['尊重 prefers-reduced-motion'],
    },
    confuseWith: [{ id: 'carousel', note: '轮播常有控件；吸附是原生滚动行为' }],
  },
  {
    id: 'scrollspy',
    nameZh: '滚动监听导航',
    nameEn: 'Scrollspy',
    category: 'navigation',
    summary: '根据当前可见区块自动高亮目录项。',
    definition: '用 Intersection Observer 追踪章节可见性，同步侧栏/顶栏目录高亮与可选滚动。',
    whenToUse: ['长文档、设置页、组件文档'],
    whenNotToUse: ['短页无需目录'],
    variants: ['点击滚动', '纯高亮', '进度条结合'],
    related: ['breadcrumb', 'sticky-header'],
    collab: {
      states: ['activeSection'],
      api: ['前端即可；深链对应 section id'],
      productNotes: ['点击目录应平滑滚动并暂时忽略 spy 抖动'],
    },
    confuseWith: [{ id: 'tabs', note: 'Tabs 切换面板；Scrollspy 仍是同一长页' }],
  },
  {
    id: 'split-pane',
    nameZh: '可调整分栏',
    nameEn: 'Resizable Split Pane',
    category: 'controls',
    summary: '拖动分割线调整相邻面板宽度，适配主从布局。',
    definition: '两栏或多栏之间的拖拽分隔条，支持键盘微调与双击重置。',
    whenToUse: ['邮件、IDE、设计工具、文档+预览'],
    whenNotToUse: ['移动窄屏（应改为堆叠或抽屉）'],
    variants: ['水平', '垂直', '多分割'],
    related: ['drawer', 'master-detail'],
    collab: {
      states: ['sizes', 'dragging'],
      api: ['把宽度存 user preference'],
      productNotes: ['设最小宽度，避免拖死'],
    },
    confuseWith: [{ id: 'drawer', note: '抽屉是叠加层；分栏是常驻布局' }],
  },
  {
    id: 'accordion',
    nameZh: '手风琴折叠',
    nameEn: 'Accordion',
    category: 'controls',
    summary: '分段内容可展开收起，常用于 FAQ 与设置分组。',
    definition: '一组可折叠面板，通常同时只展开一项或允许多开。',
    whenToUse: ['FAQ、密集设置、移动端节省纵空间'],
    whenNotToUse: ['用户需要同时比较两段全文'],
    variants: ['单开', '多开', '嵌套'],
    related: ['show-more', 'tabs'],
    collab: {
      states: ['openIds[]'],
      api: ['可写入 URL 以便分享某节'],
      productNotes: ['标题要能独立理解'],
    },
    confuseWith: [{ id: 'show-more', note: '展示更多是截断展开；手风琴是多段结构' }],
  },
  {
    id: 'inline-edit',
    nameZh: '内联编辑',
    nameEn: 'Inline Edit',
    category: 'input',
    summary: '在列表或标题上直接编辑，无需跳转表单页。',
    definition: '点击文本变为输入态，失焦或回车保存，Esc 取消。',
    whenToUse: ['改名、改短字段、表格单元格'],
    whenNotToUse: ['复杂多字段校验（用表单）'],
    variants: ['单击编辑', '显式编辑图标', '双击编辑'],
    related: ['optimistic-ui', 'autosave', 'inline-validation'],
    collab: {
      states: ['view', 'editing', 'saving', 'error'],
      api: ['PATCH 单字段；冲突用 etag'],
      productNotes: ['保存失败要回到编辑态并保留输入'],
    },
    confuseWith: [{ id: 'modal', note: '弹窗编辑打断流；内联保持上下文' }],
  },
  {
    id: 'bulk-action-bar',
    nameZh: '批量操作栏',
    nameEn: 'Bulk Action Bar',
    category: 'controls',
    summary: '多选后浮现的工具条，对选中项执行统一操作。',
    definition: '进入多选后出现数量与批量动作（删除、移动、导出），完成或清空选择后收起。',
    whenToUse: ['管理后台、邮件、资源库'],
    whenNotToUse: ['几乎从不批量的轻量列表'],
    variants: ['顶部条', '底部条', '悬浮条'],
    related: ['swipe-action', 'confirm-dialog'],
    collab: {
      states: ['idle', 'selecting', 'acting'],
      api: ['批量 API 或客户端扇出；返回部分失败明细'],
      productNotes: ['显示已选数量；危险操作要确认'],
    },
    confuseWith: [{ id: 'swipe-action', note: '滑动针对单行；批量栏针对多选' }],
  },
  {
    id: 'popover',
    nameZh: '弹出层',
    nameEn: 'Popover',
    category: 'overlays',
    summary: '锚定在触发器旁的轻量浮层，可容纳简单交互。',
    definition: '相对触发元素定位的非模态浮层，可含按钮、表单片段，点击外部关闭。',
    whenToUse: ['额外操作、小表单、说明+动作'],
    whenNotToUse: ['复杂长流程（用 Modal）', '仅一句话提示（用 Tooltip）'],
    variants: ['手动触发', '悬停', '富内容'],
    related: ['tooltip', 'modal', 'dropdown'],
    collab: {
      states: ['open', 'closed'],
      api: ['打开时可懒加载内容'],
      productNotes: ['注意焦点返回触发器'],
    },
    confuseWith: [{ id: 'tooltip', note: 'Tooltip 偏只读短文案；Popover 可交互' }],
  },
  {
    id: 'coach-mark',
    nameZh: '聚光引导',
    nameEn: 'Coach Mark / Spotlight',
    category: 'advanced',
    summary: '遮罩高亮单一控件，分步介绍新功能。',
    definition: '半透明遮罩挖出目标区域并配文案与下一步，用于首次使用导览。',
    whenToUse: ['大改版、新功能首曝', '复杂工具的关键入口'],
    whenNotToUse: ['每次登录都强制（易厌恶）', '目标不明确'],
    variants: ['单步', '多步导览', '可跳过'],
    related: ['tooltip', 'modal'],
    collab: {
      states: ['stepIndex', 'dismissed', 'completed'],
      api: ['记录 user.onboarding.completed'],
      productNotes: ['可跳过；步数 ≤ 5'],
    },
    confuseWith: [{ id: 'tooltip', note: '常驻提示 vs 一次性导览' }],
  },
  {
    id: 'typing-indicator',
    nameZh: '输入中指示',
    nameEn: 'Typing Indicator',
    category: 'collab',
    summary: '显示对方正在输入，提升对话临场感。',
    definition: '在会话中以动画圆点或文案表示对方输入中，通常防抖消失。',
    whenToUse: ['即时通讯、客服、协同评论'],
    whenNotToUse: ['非实时产品强行伪装'],
    variants: ['圆点', '「正在输入」文案', '多人合并'],
    related: ['collaborative-cursors', 'presence'],
    collab: {
      states: ['typing', 'idle'],
      api: ['ephemeral 事件，勿持久化'],
      productNotes: ['隐私：可关闭「显示我正在输入」'],
    },
    confuseWith: [{ id: 'streaming-output', note: '一个是人在输入；一个是模型在生成' }],
  },
  {
    id: 'collaborative-cursors',
    nameZh: '协同光标',
    nameEn: 'Collaborative Cursors',
    category: 'collab',
    summary: '实时显示其他协作者的光标与选区。',
    definition: '把远端用户指针位置与选区渲染到画布/文档上，通常带颜色与名字标签。',
    whenToUse: ['白板、设计协作、同时编辑'],
    whenNotToUse: ['只读文档无协作价值'],
    variants: ['仅光标', '光标+选区', '头像跟随'],
    related: ['typing-indicator', 'presence'],
    collab: {
      states: ['peers[]'],
      api: ['高频位置用 WebSocket；节流发送'],
      productNotes: ['可暂时隐藏他人光标减少干扰'],
    },
    confuseWith: [{ id: 'presence', note: '在线状态是人在不在；光标是人在哪' }],
  },
  {
    id: 'mention',
    nameZh: '@提及',
    nameEn: 'Mention',
    category: 'collab',
    summary: '输入 @ 唤起人员/实体列表并插入引用。',
    definition: '在编辑器中键入 @ 弹出候选，选择后插入可点击的提及令牌并触发通知。',
    whenToUse: ['评论、任务指派、文档协作'],
    whenNotToUse: ['无通知闭环的纯展示'],
    variants: ['人', '人+文档', '多人'],
    related: ['chip-input', 'command-palette'],
    collab: {
      states: ['query', 'picking', 'inserted'],
      api: ['搜索成员；提交含 mention ids'],
      productNotes: ['权限不足的人勿出现在列表'],
    },
    confuseWith: [{ id: 'suggestion-chips', note: '芯片是预设建议；提及是寻址某人' }],
  },
  {
    id: 'copy-feedback',
    nameZh: '复制反馈',
    nameEn: 'Copy to Clipboard Feedback',
    category: 'feedback',
    summary: '一键复制后按钮态或 Toast 确认成功。',
    definition: '调用剪贴板 API 后，用短暂的「已复制」状态替代原按钮文案或弹出 Toast。',
    whenToUse: ['API Key、邀请链接、代码片段'],
    whenNotToUse: ['无剪贴板权限且无降级'],
    variants: ['按钮变勾', 'Toast', '两者结合'],
    related: ['toast', 'optimistic-ui'],
    collab: {
      states: ['idle', 'copied', 'failed'],
      api: ['navigator.clipboard；失败时选中文本降级'],
      productNotes: ['密钥类复制后提醒妥善保管'],
    },
    confuseWith: [{ id: 'toast', note: 'Toast 是载体；复制反馈是具体任务模式' }],
  },
  {
    id: 'autosave',
    nameZh: '自动保存',
    nameEn: 'Autosave',
    category: 'input',
    summary: '静默按变更保存，并显示「保存中/已保存」状态。',
    definition: '监听编辑防抖后自动持久化，状态区展示同步结果，降低丢稿风险。',
    whenToUse: ['长文档、设计稿、表单草稿'],
    whenNotToUse: ['每次保存都有强副作用（应显式提交）'],
    variants: ['防抖保存', '定时', '离线队列'],
    related: ['optimistic-ui', 'inline-edit', 'offline-banner'],
    collab: {
      states: ['dirty', 'saving', 'saved', 'error'],
      api: ['幂等 PUT；冲突合并策略'],
      productNotes: ['错误要可手动重试；显示最后保存时间'],
    },
    confuseWith: [{ id: 'optimistic-ui', note: '乐观更新偏即时 UI；自动保存偏持久化策略' }],
  },
  {
    id: 'wizard',
    nameZh: '步进向导',
    nameEn: 'Wizard / Stepper',
    category: 'navigation',
    summary: '把复杂任务拆成有序步骤，降低一次填完的压力。',
    definition: '多步流程带步骤指示、上一步/下一步与可选的步骤校验。',
    whenToUse: ['开通、导入、复杂申请'],
    whenNotToUse: ['仅 2 个短字段（过度设计）'],
    variants: ['线性', '可跳步', '分支步骤'],
    related: ['tabs', 'progress-determinate'],
    collab: {
      states: ['step', 'valid[]', 'submitting'],
      api: ['可分步提交或最后一次提交；保存草稿'],
      productNotes: ['标明可选步；允许返回修改'],
    },
    confuseWith: [{ id: 'tabs', note: 'Tabs 同级切换；向导有先后依赖' }],
  },
  {
    id: 'faceted-search',
    nameZh: '分面筛选',
    nameEn: 'Faceted Search',
    category: 'input',
    summary: '多维度交叉过滤，边选边看结果数量变化。',
    definition: '侧栏或顶栏提供多个属性面（品牌、价格、标签），选中后结果与各面计数更新。',
    whenToUse: ['电商、资源库、日志检索'],
    whenNotToUse: ['维度极少的简单列表'],
    variants: ['多选面', '单选面', '范围面'],
    related: ['debounced-search', 'bulk-action-bar'],
    collab: {
      states: ['filters', 'resultCount'],
      api: ['facet counts 与 hits 同响应；URL 同步筛选'],
      productNotes: ['支持一键清空；显示命中数'],
    },
    confuseWith: [{ id: 'debounced-search', note: '关键词 vs 结构化多面过滤' }],
  },
  {
    id: 'hover-card',
    nameZh: '悬停预览卡',
    nameEn: 'Hover Card',
    category: 'advanced',
    summary: '悬停链接/头像时浮出实体预览，减少跳转。',
    definition: '指针悬停短暂延迟后展示预览卡片，移入卡片可继续交互，离开关闭。',
    whenToUse: ['人、文档、卡片的快速预览', '桌面端'],
    whenNotToUse: ['触控为主（无悬停）', '预览内容过重'],
    variants: ['人', '文档', '可点进详情'],
    related: ['popover', 'tooltip'],
    collab: {
      states: ['idle', 'prefetch', 'open'],
      api: ['悬停预取；取消过期请求'],
      productNotes: ['延迟 ~300ms 防误触；键盘焦点也要可开'],
    },
    confuseWith: [{ id: 'tooltip', note: 'Tooltip 短文本；Hover Card 是富预览' }],
  },
  {
    id: 'otp-input',
    nameZh: '验证码分位输入',
    nameEn: 'OTP Input',
    category: 'input',
    summary: '多格一位一格，支持粘贴与自动跳格。',
    definition: '将验证码拆成固定格，输入自动前进，退格回退，整串粘贴时拆分填入。',
    whenToUse: ['登录二次验证、绑定手机'],
    whenNotToUse: ['任意长度密码'],
    variants: ['4/6 位', '密码遮罩', '自动提交'],
    related: ['inline-validation'],
    collab: {
      states: ['empty', 'filling', 'complete', 'error'],
      api: ['提交后校验；错误清空或保留'],
      productNotes: ['支持短信自动填充 autocomplete=one-time-code'],
    },
    confuseWith: [{ id: 'inline-validation', note: 'OTP 是特定输入形态' }],
  },
  {
    id: 'drag-drop-upload',
    nameZh: '拖放上传',
    nameEn: 'Drag-and-drop Upload',
    category: 'input',
    summary: '将文件拖入放置区，展示进度与状态。',
    definition: '放置区响应 dragover/drop，校验类型与大小后上传并显示进度。',
    whenToUse: ['资源上传、附件', '桌面端提效'],
    whenNotToUse: ['仅移动端且系统分享更合适'],
    variants: ['单文件', '多文件队列', '文件夹'],
    related: ['progress-determinate', 'toast'],
    collab: {
      states: ['idle', 'dragging', 'uploading', 'done', 'error'],
      api: ['直传或预签名 URL；分片'],
      productNotes: ['同时提供点击选择文件'],
    },
    confuseWith: [{ id: 'drag-reorder', note: '上传 vs 排序' }],
  },
  {
    id: 'virtual-list',
    nameZh: '虚拟列表',
    nameEn: 'Virtual List',
    category: 'scrolling',
    summary: '只渲染可视区附近的行，撑起超长列表性能。',
    definition: '根据滚动位置计算可见窗口，仅挂载窗口内 DOM，外层用总高度撑开滚动条。',
    whenToUse: ['成千上万行的日志、通讯录、表格'],
    whenNotToUse: ['几十行以内（过度工程）'],
    variants: ['定高', '动态高度', '表格虚拟化'],
    related: ['infinite-scroll', 'skeleton'],
    collab: {
      states: ['windowStart', 'windowEnd'],
      api: ['可与游标分页结合'],
      productNotes: ['无障碍：确保焦点行仍可聚焦'],
    },
    confuseWith: [{ id: 'infinite-scroll', note: '虚拟化管渲染；无限滚动管取数' }],
  },
  {
    id: 'sticky-header',
    nameZh: '粘性头',
    nameEn: 'Sticky Header',
    category: 'navigation',
    summary: '滚动时表头或工具栏固定在视口边缘。',
    definition: '使用 sticky 定位让标题行在滚动中保持可见，便于对照列含义或保留操作。',
    whenToUse: ['长表格、长列表工具栏'],
    whenNotToUse: ['短内容；多个 sticky 互相抢空间'],
    variants: ['表头', '分区粘性', '带阴影提示'],
    related: ['scrollspy', 'bulk-action-bar'],
    collab: {
      states: ['stuck'],
      api: ['纯 CSS/前端'],
      productNotes: ['注意与顶栏高度叠加'],
    },
    confuseWith: [{ id: 'scrollspy', note: '粘性是位置固定；spy 是高亮同步' }],
  },
  {
    id: 'show-more',
    nameZh: '截断展开',
    nameEn: 'Show More / Truncation',
    category: 'controls',
    summary: '长文本先截断，按需展开全文。',
    definition: '超出 N 行或字符后显示「展开」，展开后可「收起」。',
    whenToUse: ['评论、描述、搜索结果摘要'],
    whenNotToUse: ['法律全文必须默认完整可见'],
    variants: ['行数截断', '字符截断', '渐变遮罩'],
    related: ['accordion'],
    collab: {
      states: ['collapsed', 'expanded'],
      api: ['可先返回摘要字段'],
      productNotes: ['展开后保持阅读位置'],
    },
    confuseWith: [{ id: 'accordion', note: '截断是单块文本；手风琴是多段标题' }],
  },
  {
    id: 'morph-button',
    nameZh: '形态变化按钮',
    nameEn: 'Morphing / Stateful Button',
    category: 'advanced',
    summary: '按钮在默认、加载、成功之间变形反馈，无需整页刷新。',
    definition: '同一按钮槽位在 idle → loading → success/error 间过渡宽高与内容。',
    whenToUse: ['提交、支付、发送等关键 CTA'],
    whenNotToUse: ['状态切换过快造成闪烁'],
    variants: ['变 Spinner', '变勾', '扩展为进度条'],
    related: ['progress-determinate', 'optimistic-ui'],
    collab: {
      states: ['idle', 'loading', 'success', 'error'],
      api: ['请求期间禁用重复点击'],
      productNotes: ['成功态停留可感知时长再复位'],
    },
    confuseWith: [{ id: 'progress-determinate', note: '进度条可独立；形态按钮是 CTA 自身反馈' }],
  },
  {
    id: 'kanban-dnd',
    nameZh: '看板拖拽',
    nameEn: 'Kanban Drag-and-drop',
    category: 'controls',
    summary: '在列之间拖动卡片以改变状态或分组。',
    definition: '多列容器，卡片可跨列拖放，落列即映射为状态变更。',
    whenToUse: ['任务流、招聘漏斗、工单'],
    whenNotToUse: ['状态变更需复杂表单（应打开详情）'],
    variants: ['同列排序', '跨列', '泳道'],
    related: ['drag-reorder', 'optimistic-ui'],
    collab: {
      states: ['columns', 'dragging'],
      api: ['更新 status+order；冲突处理'],
      productNotes: ['非法落列要拒收并提示原因'],
    },
    confuseWith: [{ id: 'drag-reorder', note: '单列表排序 vs 多列状态板' }],
  },
  {
    id: 'context-menu',
    nameZh: '上下文菜单',
    nameEn: 'Context Menu',
    category: 'overlays',
    summary: '右键或长按在指针处打开与对象相关的操作菜单。',
    definition: '在目标上二次指针动作弹出菜单，菜单项随对象类型变化。',
    whenToUse: ['桌面效率场景、画布、文件树'],
    whenNotToUse: ['移动端优先且已有明显按钮'],
    variants: ['右键', '长按', '自定义触发'],
    related: ['popover', 'command-palette'],
    collab: {
      states: ['open', 'closed'],
      api: ['菜单项可按权限过滤'],
      productNotes: ['提供键盘 Shift+F10 等价'],
    },
    confuseWith: [{ id: 'popover', note: '上下文菜单强依赖指针位置与对象' }],
  },
  {
    id: 'selection-toolbar',
    nameZh: '选区浮动工具条',
    nameEn: 'Selection Toolbar',
    category: 'advanced',
    summary: '选中文本后在附近浮出加粗、评论、AI 改写等操作。',
    definition: '监听选区变化，在 range 旁定位工具条，点击执行格式化或唤起能力。',
    whenToUse: ['文档编辑、批注、AI 写作'],
    whenNotToUse: ['只读且无选区动作'],
    variants: ['格式', '评论', 'AI'],
    related: ['inline-edit', 'mention'],
    collab: {
      states: ['no_selection', 'toolbar_open'],
      api: ['操作携带 selection range'],
      productNotes: ['滚动/选区变化时更新位置'],
    },
    confuseWith: [{ id: 'popover', note: '由选区驱动而非按钮触发' }],
  },
  {
    id: 'offline-banner',
    nameZh: '离线提示',
    nameEn: 'Offline Banner',
    category: 'feedback',
    summary: '网络断开时顶栏提示，恢复后自动消失或可同步。',
    definition: '监听 online/offline，展示持久横幅；恢复时可提示「待同步变更」。',
    whenToUse: ['可离线编辑或强依赖网络的 App'],
    whenNotToUse: ['纯静态宣传页'],
    variants: ['只读提示', '排队同步', '重试'],
    related: ['autosave', 'toast'],
    collab: {
      states: ['online', 'offline', 'syncing'],
      api: ['本地队列；上线后 flush'],
      productNotes: ['说清哪些功能不可用'],
    },
    confuseWith: [{ id: 'banner', note: '离线是系统状态特化横幅' }],
  },
  {
    id: 'empty-state',
    nameZh: '空状态',
    nameEn: 'Empty State',
    category: 'feedback',
    summary: '无数据时解释原因并给出明确下一步。',
    definition: '列表/画布为空时展示说明、插图与主行动（创建、导入、连接）。',
    whenToUse: ['首次使用、筛选无结果、权限导致为空'],
    whenNotToUse: ['加载中（应用骨架/Spinner）'],
    variants: ['首次', '无结果', '无权限'],
    related: ['skeleton', 'faceted-search'],
    collab: {
      states: ['empty'],
      api: ['区分 zero-data vs filtered-empty'],
      productNotes: ['主按钮一个；文案避免指责用户'],
    },
    confuseWith: [{ id: 'skeleton', note: '空是真没有；骨架是还在加载' }],
  },
  {
    id: 'parallax',
    nameZh: '视差滚动',
    nameEn: 'Parallax Scroll',
    category: 'advanced',
    summary: '多层以不同速率滚动，营造深度与氛围。',
    definition: '背景与前景绑定不同滚动系数，产生视差；需提供减弱动效降级。',
    whenToUse: ['品牌叙事、营销首屏'],
    whenNotToUse: ['数据密集工具页', '晕动敏感场景未降级'],
    variants: ['图层位移', '缩放视差'],
    related: ['scroll-snap'],
    collab: {
      states: ['scrollY'],
      api: ['前端'],
      productNotes: ['prefers-reduced-motion 时关闭'],
    },
    confuseWith: [{ id: 'scroll-snap', note: '吸附是停靠；视差是速率差' }],
  },
  {
    id: 'shared-element',
    nameZh: '共享元素过渡',
    nameEn: 'Shared Element Transition',
    category: 'advanced',
    summary: '列表缩略图「飞入」详情，建立空间连续感。',
    definition: '同一视觉元素在两屏间连续位移缩放，常见于画廊与卡片进详情。',
    whenToUse: ['媒体库、商品卡进详情', '强化心智模型'],
    whenNotToUse: ['无共享视觉锚点的路由'],
    variants: ['图片英雄', '卡片扩展'],
    related: ['morph-button', 'modal'],
    collab: {
      states: ['list', 'animating', 'detail'],
      api: ['前端动画；可配合 View Transitions API'],
      productNotes: ['中断要可取消；减少动效时瞬切'],
    },
    confuseWith: [{ id: 'modal', note: '模态是打断；共享元素强调连续' }],
  },
  {
    id: 'chip-input',
    nameZh: '芯片输入',
    nameEn: 'Chip / Tag Input',
    category: 'input',
    summary: '把多项做成可删除芯片，适合收件人与标签。',
    definition: '输入框内以芯片展示已选项，回车/逗号生成芯片，Backspace 删除末项。',
    whenToUse: ['邮件收件人、标签、多选关键词'],
    whenNotToUse: ['单项输入'],
    variants: ['自由输入', '仅可选列表', '粘贴拆分'],
    related: ['mention', 'faceted-search'],
    collab: {
      states: ['chips[]', 'draft'],
      api: ['提交 id 或字符串数组'],
      productNotes: ['重复项提示；校验失败芯片标红'],
    },
    confuseWith: [{ id: 'suggestion-chips', note: '输入芯片可编辑集合；建议芯片是快捷选项' }],
  },
  {
    id: 'presence',
    nameZh: '在线状态',
    nameEn: 'Presence',
    category: 'collab',
    summary: '头像旁显示在线/离开/忙碌等实时状态。',
    definition: '通过心跳或连接状态展示用户可用性，常与头像叠角标。',
    whenToUse: ['协作套件、客服坐席、即时通讯'],
    whenNotToUse: ['无实时意义的内容站'],
    variants: ['绿点', '文案状态', '隐身'],
    related: ['typing-indicator', 'collaborative-cursors'],
    collab: {
      states: ['online', 'away', 'offline', 'busy'],
      api: ['presence channel；超时判离线'],
      productNotes: ['提供隐身/勿扰'],
    },
    confuseWith: [{ id: 'collaborative-cursors', note: '在不在 vs 在哪' }],
  },
]
